import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import localFont from "next/font/local";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], 
});

const swungNote = localFont({
    src: "../public/fonts/SwungNote.otf",
    variable: "--font-swung",
});

export const metadata: Metadata = {
    title: "Pilketos",
    description: "Generated by create next z",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <NuqsAdapter>
                <body
                    className={`${swungNote.variable} ${poppins.variable} antialiased dark`}
                >
                    {children}
                    <Toaster position="top-right" />
                </body>
            </NuqsAdapter>
        </html>
    );
}
